### PR TITLE
added a few more sections and solutions for leetcode problems

### PR DESCRIPTION
**Pull request by GunjanMA**

### CODE REVIEW

**Review by sunnysetia93 — COMMENTED** [review]
Great Job.
Just one suggestion, It would be better if you can add code to run the solution class/struct.
Create an object and call the function with appropriate params

Gives the user an understanding of how to use the solution.

**Comment by GunjanMA** [comment]
> Great Job.
> Just one suggestion, It would be better if you can add code to run the solution class/struct.
> Create an object and call the function with appropriate params
> 
> Gives the user an understanding of how to use the solution.

Sure... I will do it

**Comment by GunjanMA** [comment]
Please merge this PR and then I'll again make a new PR to add the code to run the solution

**Comment by sunnysetia93** [comment]
> Please merge this PR and then I'll again make a new PR to add the code to run the solution

You can update this PR itself as it is the same solution.

**Comment by GunjanMA** [comment]
how can we update a PR ??? please guide... I'm a noob

**Comment by sunnysetia93** [comment]
> how can we update a PR ??? please guide... I'm a noob

Sure.
in the forked repo, pull the new changes from master
add a new commit with updated changes in the file
push it to your branch and create a pull request - will be added to the existing PR automatically.

**Comment by bhavidhingra** [comment]
I've updated the directory structure of leetCode_ques directory in my PR #14 
It would be helpful if we can follow it.

**Comment by GunjanMA** [comment]
@sunnysetia93 I've added the driver code for stack and bit manipulation. For Trees, It depends on how the user creates the BuildTree function and takes input (level/pre/post order)... Hence I didn't update it

**Review by sunnysetia93 — APPROVED** [review]

**Comment by sunnysetia93** [comment]
> @sunnysetia93 I've added the driver code for stack and bit manipulation. For Trees, It depends on how the user creates the BuildTree function and takes input (level/pre/post order)... Hence I didn't update it

No Issues
As pointed out by @bhavidhingra we should be following a proper folder structure and filename conventions
@bhavidhingra will soon be updating the contributions.md with the desired conventions.
Please follow these guidelines the next time you contribute. Thanks 👍

**Comment by sunnysetia93** [comment]
> I've updated the directory structure of leetCode_ques directory in my PR #14
> It would be helpful if we can follow it.

Great. Nice suggestion @bhavidhingra 
I have reviewed your PR. can you check and perform the necessary action?

Thanks

**Pull request merged**
